version: "3.3"
services:
  oauth:
    image: quay.io/keycloak/keycloak:23.0.7
    ports:
      - 8085:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
    volumes:
      - ./oauth/openhouse-realm.json:/opt/keycloak/data/import/openhouse-realm.json:ro
    command: ["start-dev", "--import-realm"]