scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      # making the prometheus scraping from the service exposed in each container's port
      - targets: ['local.openhouse-tables:8080', 'local.openhouse-jobs:8080']