name: OpenHouse Table Service Image

on:
  workflow_run:
    workflows:
      - Gradle Build, Tag, and Publish OpenHouse
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: get_tag
        if: ${{ success() }}
        run: |
          latest_tag=$(git describe --tags --abbrev=0 main)
          semVer=${latest_tag:1} # Remove the first character ('v')
          echo "::set-output name=semVer::${semVer}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sushihub
          password: dckr_pat_cSrHhol6R8rGiZ8PIKjx7op9jmY

      - name: Build and Push
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name == 'main' }}
        env:
          IMAGE_TAG: ${{ steps.get_tag.outputs.semVer }}
        with:
          context: ./
          file: tables-service.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sushihub/tables-service:latest,sushihub/tables-service:${{ steps.get_tag.outputs.semVer }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name == 'main' }}
        env:
          IMAGE_TAG: ${{ steps.get_tag.outputs.semVer }}
        with:
          context: ./
          file: jobs-service.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sushihub/jobs-service:latest,sushihub/jobs-service:${{ steps.get_tag.outputs.semVer }}
